### ISSUE TITLE
Hello

### ISSUE THREAD

**Issue by xiaojia998** [karnadii/marvelous65#1]
I don’t know if I can buy one of your pcbs. Can I add a discord or WeChat easily?

**Comment by karnadii** [comment]
Thanks for your interest in my marvelous65. there are some minor mistake in
my version 2 pcb. So i need more revision. I don't sell my marvelous65 yet.
But don't worry, I plan to make it open source. So you have to wait a
little bit, cause I don't have the time to do revision yet. I will put
donate link in the future in github. So if you feel gratitude you can
donate to me latter.

Thank you.

**Comment by xiaojia998** [comment]
Thank you for your reply, looking forward to future v2, I would love to donate if I can!

**Comment by karnadii** [comment]
My discord is karnadi#6627 if you want in touch. I dont have a wechat
currently.

**Comment by karnadii** [comment]
Just pushed the pcb files to the repo, if you are still interested you can order the pcb at JLC or pcbway your own

**Comment by xiaojia998** [comment]
> 只需将pcb文件推送到仓库中，如果您仍然有兴趣，可以在JLC或pcbway上订购pcb

Thanks for sharing, I've got the pcb file and placed an order with JLC, how do I get the relevant firmware?

**Comment by karnadii** [comment]
don't worry with the firmware, everything ready. I will link it to readme when I finish organizing the files.

**Comment by xiaojia998** [comment]
Great, thanks!
