### ISSUE TITLE
[POLL] Which one do you like the most?

### ISSUE THREAD

**Issue by karnadii** [karnadii/marvelous65#2]
Please vote, which one you like the most so I can focus on developing the case pcb and the feature more.

1. Original version
2. Ergo version
3. Split version

also if you building one and have a question, let me know in the comment bellow or via discord karnadi#6627

**Comment by drewfowler** [comment]
Ergo!

**Comment by karnadii** [comment]
> Ergo!

Right, in the beginning I focus on the regular version, now I can't go back to the regular version since I use the ergo/alice like version. I am planning to add more feature like trackpoint and other feature on the ergo version, since the pcb has more space than the regular version. I just wait for the ZMK support ready first untill I add another feature.

**Comment by drewfowler** [comment]
I think it is awesome how it is. It is the top board on my list to build.

**Comment by aotd1** [comment]
Split! =)
I'm trying to find a split true wireless keyboard for a few months, and the lasts I found!
The last thing that stops me - there is no hot-swap for the split version. And I can't find nice!nano boards to buy (is it true that this project uses it?)

**Comment by karnadii** [comment]
I don't have the time to make the the hotswap version yet, if you know some kicad you can edit it yourself. Honestly the split version was poorly designed, I am too lazy to make the case and pcb. The case should be universal (compatible all layout).

**Comment by karnadii** [comment]
My split use nrfmicro https://github.com/joric/nrfmicro
Kind of nice!nano replacement (DIY). Or you can use bluemicro too https://store.jpconstantineau.com/#/item/BMicro840

**Comment by aotd1** [comment]
Thanks, I hope I'll have enough free time to make some pull requests to "make split great again" =)

**Comment by vuh95** [comment]
Ergo!!!

I like Alice layout.

**Comment by Opiowo** [comment]
Split

**Comment by karnadii** [comment]
> Ergo!!!
> 
> I like Alice layout.

actually I am working on wireless alice right now, build according alice plate, should be compatible with alice clone case (not proven yet). ![](https://cdn.discordapp.com/attachments/584768133219221517/849565395857178634/Screen_Shot_2021-06-02_at_15.23.54.png)

**Comment by huythong1991** [comment]
Normal and Ergo !!!!!

**Comment by vuh95** [comment]
> > Ergo!!!
> > I like Alice layout.
> 
> actually I am working on wireless alice right now, build according alice plate, should be compatible with alice clone case (not proven yet). ![](https://camo.githubusercontent.com/e25443638af833737167ee9c0a33c2df5e52703e7751f1d2c92f1826ddf47265/68747470733a2f2f63646e2e646973636f72646170702e636f6d2f6174746163686d656e74732f3538343736383133333231393232313531372f3834393536353339353835373137383633342f53637265656e5f53686f745f323032312d30362d30325f61745f31352e32332e35342e706e67)

I am really looking forward to seeing the wireless version.
